-- 1. Create Sequence for Users Entity
CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

-- 2. Create Users Table
CREATE TABLE users (
    id BIGINT NOT NULL DEFAULT nextval('users_seq'),
    email_address VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    full_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    registered_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    roles VARCHAR(255)[],
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email_address UNIQUE (email_address)
);

-- 3. Create Customer Table
CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    balance NUMERIC(38,2),
    phone_number VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id),
    CONSTRAINT uk_customer_user_id UNIQUE (user_id),
    CONSTRAINT fk_customer_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 4. Create Transaction Table
CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount NUMERIC(38,2),
    transaction_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    transaction_type VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT transaction_pkey PRIMARY KEY (id),
    CONSTRAINT check_transaction_type CHECK (transaction_type IN ('FUND_WALLET', 'TRANSFER_MONEY', 'WITHDRAW_MONEY', 'BUY_AIRTIME')),
    CONSTRAINT fk_transaction_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 5. Create Verification Tokens Table
CREATE TABLE verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    expire_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    expired BOOLEAN DEFAULT FALSE,
    generated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    revoked BOOLEAN DEFAULT FALSE,
    token VARCHAR(255) NOT NULL,
    CONSTRAINT verification_tokens_pkey PRIMARY KEY (id)
);

-- 6. Create Xpress Tokens Table
CREATE TABLE xpress_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    access_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    expired BOOLEAN DEFAULT FALSE,
    refresh_token VARCHAR(255) NOT NULL,
    revoked BOOLEAN DEFAULT FALSE,
    user_id BIGINT NOT NULL,
    CONSTRAINT xpress_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT fk_xpress_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 7. Create Airtime Purchase Table
CREATE TABLE airtime_purchase (
    id VARCHAR(255) NOT NULL,
    amount NUMERIC(38,2) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    transaction_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    unique_code VARCHAR(255) NOT NULL,
    user_id BIGINT,
    CONSTRAINT airtime_purchase_pkey PRIMARY KEY (id),
    CONSTRAINT check_airtime_purchase_status CHECK (status IN ('PENDING', 'SUCCESSFUL', 'FAILED')),
    CONSTRAINT fk_airtime_purchase_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);
